### PR TITLE
Zip, zip, hurra

### LINKED ISSUE #36: Deliver result as archives
Currently, only a folder of csv files is delivered. Add the functionality to deliver them as archives.

### PR DESCRIPTION
**Pull request by ckittl**
Closes #36 
~Take care of #35 before.~

### CODE REVIEW

**Comment by ckittl** [comment]
**Let op!** Currently there are issues writing csv files using a defined directory hierarchy. Before addressing this PR please wait for ie3-institute/PowerSystemDataModel#230 to be fixed.

**Comment by ckittl** [comment]
!test

**Comment by ckittl** [comment]
!test

**Review by johanneshiry — APPROVED** [review]
LGTM 👍  - I'm just wondering why you didn't use the existing implementation for handling .zip files in PowerSystemUtils (https://github.com/ie3-institute/PowerSystemUtils/blob/2053811dc8243eff776ce9a06ee65948bbb48a42/src/main/java/edu/ie3/util/io/FileIOUtils.java#L110)? While providing methods for zipping I think they would benefit from providing methods for unzipping as well ... you might consider using these methods instead and provide additional unzipping methods there?!

**Comment by ckittl** [comment]
> LGTM 👍 - I'm just wondering why you didn't use the existing implementation for handling .zip files in PowerSystemUtils (https://github.com/ie3-institute/PowerSystemUtils/blob/2053811dc8243eff776ce9a06ee65948bbb48a42/src/main/java/edu/ie3/util/io/FileIOUtils.java#L110)? While providing methods for zipping I think they would benefit from providing methods for unzipping as well ... you might consider using these methods instead and provide additional unzipping methods there?!

Oh, didn't knew the implementation there. I think it is worthwhile to join the approach in PowerSystemDataModel and PowerSystemUtils there. But I prefer to do this in a separate PR.

**Pull request merged**
